# Generated by Django 2.1.7 on 2019-07-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JsonDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
            ],
            options={
                'verbose_name': 'JSON Datum',
                'verbose_name_plural': 'JSON Data',
            },
        ),
    ]
