# Generated by Django 2.1.7 on 2019-07-24 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JSONFileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36)),
                ('datafile', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
